name: cypress-test-combi
on:
  workflow_dispatch:

jobs:

  start:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16, 18]
    name: Angular E2E test on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm ci

      - name: Start server
        run: npx start-server-and-test start http://localhost:4200 "npm run-script defer-test" &

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
